### ISSUE TITLE
Responsiveness 

### ISSUE THREAD

**Issue by ishikapoddar** [jayk-gupta/web-resources-project#10]
The side bar and the navbar is not responsive, assign this issue to me under, gssoc 2023

**Comment by Avinash905** [comment]
I would like to work on this issue under GSSOC-23

**Comment by Anushka20365** [comment]
Hello @jayk-gupta  ,
I'm Anushka Anand . I want to work on this issue under Gssoc'23. I am really eager to work on open source projects and contribute to this community.I've taken a look at the codebase and I believe I can make some valuable improvements. I'll start working on it right away.

Skills
HTML5, CSS3, JS, Bootstrap | Python, Django | Php, mysql | MERN | Responsive Design | Adobe Photoshop |

Can you please assign this issue to me.

**Comment by jayk-gupta** [comment]
> The side bar and the navbar is not responsive, assign this issue to me under, gssoc 2023

Yes, you can work on it!
I will assign you after today's meet of GSSoC

**Comment by jayk-gupta** [comment]
> The side bar and the navbar is not responsive, assign this issue to me under, gssoc 2023

Are you familiar with Tailwindcss for making the site responsiveness?

**Comment by Avinash905** [comment]
> > The side bar and the navbar is not responsive, assign this issue to me under, gssoc 2023
> 
> Are you familiar with Tailwindcss for making the site responsiveness?

I am familiar with TailwindCss

**Comment by jayk-gupta** [comment]
> > > The side bar and the navbar is not responsive, assign this issue to me under, gssoc 2023
> > 
> > 
> > Are you familiar with Tailwindcss for making the site responsiveness?
> 
> I am familiar with TailwindCss

Issues are given according to FCFS rule, if she can't do then I will give you.

**Comment by Avinash905** [comment]
> > > > The side bar and the navbar is not responsive, assign this issue to me under, gssoc 2023
> > > 
> > > 
> > > Are you familiar with Tailwindcss for making the site responsiveness?
> > 
> > 
> > I am familiar with TailwindCss
> 
> Issues are given according to FCFS rule, if she can't do then I will give you.

Ok

**Comment by villAsh** [comment]
can you assign this to me I have working knowledge of TailwindCss

**Comment by jayk-gupta** [comment]
> > > > > The side bar and the navbar is not responsive, assign this issue to me under, gssoc 2023
> > > > 
> > > > 
> > > > Are you familiar with Tailwindcss for making the site responsiveness?
> > > 
> > > 
> > > I am familiar with TailwindCss
> > 
> > 
> > Issues are given according to FCFS rule, if she can't do then I will give you.
> 
> Ok

Assigned to you!

**Comment by ishikapoddar** [comment]
Yes I am familiar with it @jayk-gupta

**Comment by jayk-gupta** [comment]
Work on it!

**Comment by jayk-gupta** [comment]
Are you working on it?

**Comment by jayk-gupta** [comment]
# Important Announcement: Closure of GitHub Repository Issues, Website Redesign, and Discord Channel Invitation

We apologize for the inconvenience caused, but we must inform you that all current issues in our repository will be closed. This decision aims to improve our development process and enhance organization.

Excitingly, we are announcing a complete redesign of our website, focused on improving user experience and incorporating new features aligned with our goals.

Please note that approximately half of the existing issues are redundant and will be closed accordingly.

We also invite you to join our Discord channel for project collaboration and communication. Visit GSSoC server and assign yourself Web Resource Hub project role using the self-roles feature.

[Join here](https://discord.com/channels/1099745007172329592/1110637817383632957)

Your feedback and support are invaluable to us. We look forward to hearing your thoughts on the upcoming changes.

Thank you for your understanding and continued support.

Sincerely,
Project Admin
