### ISSUE TITLE
[FEAT] Add lazy loading feature to the website

### ISSUE THREAD

**Issue by Avinash905** [jayk-gupta/web-resources-project#108]
**Is your feature request related to a problem? Please describe.**
Whenever the website is first loaded it downloads all the javascript files and then renders it. The files which are not displayed when it is first loaded are also downloaded which causes the website to be slow. 

**Describe the solution you'd like**
I would like to add lazy loading feature to the website so that only required files get downloaded and rendered instead of downloading all files at once. 

**Additional context**
**Is the issue already present?**
No

Please assign me this issue I would like to work on this issue under GSSOC'23

**Comment by jayk-gupta** [comment]
# Important Announcement: Closure of GitHub Repository Issues, Website Redesign, and Discord Channel Invitation
We apologize for the inconvenience caused, but we must inform you that all current issues in our repository will be closed. This decision aims to improve our development process and enhance organization.

Excitingly, we are announcing a complete redesign of our website, focused on improving user experience and incorporating new features aligned with our goals.

Please note that approximately half of the existing issues are redundant and will be closed accordingly.

We also invite you to join our Discord channel for project collaboration and communication. Visit GSSoC server and assign yourself Web Resource Hub project role using the self-roles feature.

[Join here](https://discord.com/channels/1099745007172329592/1110637817383632957)

Your feedback and support are invaluable to us. We look forward to hearing your thoughts on the upcoming changes.

Thank you for your understanding and continued support.

Sincerely,
Project Admin
