### ISSUE TITLE
Remove console messages

### ISSUE THREAD

**Issue by Avinash905** [jayk-gupta/web-resources-project#11]
![Screenshot (413)](https://github.com/jayk-gupta/web-resources-project/assets/56786344/bb52ef83-2be6-4ea9-8d29-add92a81041f)

The console.log messages are appearing in the console tab.

**Comment by Avinash905** [comment]
Please assign me this issue so that I can remove the console.log messages under GSSOC-23

**Comment by jayk-gupta** [comment]
Please wait for today, the mentors haven't been assigned till now

**Comment by Avinash905** [comment]
> Please wait for today, the mentors haven't been assigned till now

Sure

**Comment by tanya2203** [comment]
Please assign this issue to me ,I would like to resolve the issue.

**Comment by Avinash905** [comment]
Can you please add the level?
