### ISSUE TITLE
[FEAT]

### ISSUE THREAD

**Issue by Jiya-garg9971** [jayk-gupta/web-resources-project#111]
**Is your feature request related to a problem? Please describe.**
When I click on any resource link it is not redirecting me to the desired website. It is very frustrating.

**Describe the solution you'd like**
Add the respective link of the resource so that when we click on a particular resource it will redirect me to that website.

Please assign this issue to me with GSSOC 2023 label.

**Comment by jayk-gupta** [comment]
Which one?
