### ISSUE TITLE
[STYLE] Books card is not responsive

### ISSUE THREAD

**Issue by Soyeb01** [jayk-gupta/web-resources-project#112]
# Description
The responsiveness of website is still unsteady , you see in the screenschot below or open the website on smaller device like mobile.

# Solution 
We can improve tailwwind CSS used.

# Screenshot
![Screenshot_20230522-095128_Chrome](https://github.com/jayk-gupta/web-resources-project/assets/98175646/b33bbaa6-88fa-46b8-a485-26c2c4c677e9)

![Screenshot_20230522-100027_Chrome](https://github.com/jayk-gupta/web-resources-project/assets/98175646/c228a560-eea1-48fe-87eb-de35ae8fc937)

**Comment by jayk-gupta** [comment]
# Important Announcement: Closure of GitHub Repository Issues, Website Redesign, and Discord Channel Invitation
We apologize for the inconvenience caused, but we must inform you that all current issues in our repository will be closed. This decision aims to improve our development process and enhance organization.

Excitingly, we are announcing a complete redesign of our website, focused on improving user experience and incorporating new features aligned with our goals.

Please note that approximately half of the existing issues are redundant and will be closed accordingly.

We also invite you to join our Discord channel for project collaboration and communication. Visit GSSoC server and assign yourself Web Resource Hub project role using the self-roles feature.

[Join here](https://discord.com/channels/1099745007172329592/1110637817383632957)

Your feedback and support are invaluable to us. We look forward to hearing your thoughts on the upcoming changes.

Thank you for your understanding and continued support.

Sincerely,
Project Admin
