### ISSUE TITLE
Update README.md to add Contributors

### ISSUE THREAD

**Issue by adjascently** [jayk-gupta/web-resources-project#114]
**Issue Description**
I would like to update the README.md to include the list of Contributors to this project. I'm in GSSoC '23

**Topic or Category**
Updating README file

**Benefits of Adding this Resource**
A major benefit of adding this resource would be to encourage people to contribute to this project as well as display the profiles of those who have already contributed.

**Comment by jayk-gupta** [comment]
Yes you can add

**Comment by jayk-gupta** [comment]
The list is not updated as new contributors are added, can you make it such that it automatically adds new contributors?
Your name is also not showing.
