### ISSUE TITLE
[FEAT] Make the Whole Card Clickable

### ISSUE THREAD

**Issue by manasi-jain** [jayk-gupta/web-resources-project#118]
**Is your feature request related to a problem? Please describe.**

- Currently, only the heading of the card is clickable, but I would like to make the entire card clickable to provide a more intuitive user experience. This will allow users to interact with the card by clicking anywhere within its boundaries, rather than limiting the click functionality to the heading alone.

**Describe the solution you'd like**
- Modify the card component to wrap the entire card content within a clickable container.
- Apply the necessary event handling or link functionality to the clickable container to enable interaction with the entire card.
- Ensure that any existing click events or functionality associated with the card heading are appropriately transferred to the new clickable container.

**Additional context**

![Will make the Whole Card Clickable](https://github.com/jayk-gupta/web-resources-project/assets/83013408/4438e3b9-ded8-41a1-84e9-21e220c8ab9b)

**Comment by jayk-gupta** [comment]
go ahead
