### ISSUE TITLE
Improving the readme file of this project 

### ISSUE THREAD

**Issue by harshsingh32** [jayk-gupta/web-resources-project#12]
I would like to work on improving the readme file of this project making it engaging for the users and make it more expressive.

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by tanya2203** [comment]
I believe I have the skills and knowledge necessary to tackle this particular issue effectively. I have successfully resolved similar problems in the past. Please assign me this issue

**Comment by lalitkumawat1m** [comment]
I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.

**Comment by harshsingh32** [comment]
Sir, I have relevant experience and skillset to improve the readme file of this project. I would improve the readme file by adding features, using catchy phrases and expressive information so that would engage the user to contribute to the project and increase the engagement of this project.

**Comment by Abhinavcode13** [comment]
please assign me this issue @jayk-gupta under gssoc 23
