### ISSUE TITLE
[BUG] Navbar Click [GSSOC'23]

### ISSUE THREAD

**Issue by parthpathakpp1** [jayk-gupta/web-resources-project#127]
**Describe the bug**
When we click on the HTML CSS JS ,REACT it does not show Welcome to HTML section and so on , rather it shows Welcome to Books section . 

**To Reproduce**
1. Click on any of the languages option on top.
2. Then look at "Welcome to Books Section"
3. That's a bug it is always showing "Books"

**Expected behavior**
Name of respective language should be there.

**Screenshots**

https://github.com/jayk-gupta/web-resources-project/assets/85991449/cabb7065-8ebb-4aad-9176-d33bc5433520

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]

**Smartphone (please complete the following information):**
 - Device: [samsung m32]
 - OS: [Android 11]
 - Browser [chrome]

**Additional context**

**Comment by jayk-gupta** [comment]
you can work on it!

**Comment by jayk-gupta** [comment]
# Important Announcement: Closure of GitHub Repository Issues, Website Redesign, and Discord Channel Invitation
We apologize for the inconvenience caused, but we must inform you that all current issues in our repository will be closed. This decision aims to improve our development process and enhance organization.

Excitingly, we are announcing a complete redesign of our website, focused on improving user experience and incorporating new features aligned with our goals.

Please note that approximately half of the existing issues are redundant and will be closed accordingly.

We also invite you to join our Discord channel for project collaboration and communication. Visit GSSoC server and assign yourself Web Resource Hub project role using the self-roles feature.

[Join here](https://discord.com/channels/1099745007172329592/1110637817383632957)

Your feedback and support are invaluable to us. We look forward to hearing your thoughts on the upcoming changes.

Thank you for your understanding and continued support.

Sincerely,
Project Admin
