### ISSUE TITLE
[FEAT] Want to add social media Icons

### ISSUE THREAD

**Issue by Lovegupta112** [jayk-gupta/web-resources-project#128]
**Is your feature request related to a problem? Please describe.**
A good website always has social media icons or Buttons so that if any user visit that website so They can follow your social media accounts, join discussions, and participate in conversations, fostering a sense of community and building stronger relationships with your audience.

**Describe the solution you'd like**
I want to add social media icons and it will be like scroll bar button type where user can click and will redirect to corresponding social media accounts 

**Additional context**
![socialmediadesign](https://github.com/jayk-gupta/web-resources-project/assets/90507983/361c6a89-f847-4f90-bc12-f79361f8e671)

**Comment by jayk-gupta** [comment]
There are no social media accounts for the website for now!
