### ISSUE TITLE
Improving the Home.jsx

### ISSUE THREAD

**Issue by harshsingh32** [jayk-gupta/web-resources-project#13]
I would like to work on improving the Home.jsx of this project making it engaging for the users. I would like to add some features and make it more expressive.

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by jayk-gupta** [comment]
work on it and show me!

**Comment by jayk-gupta** [comment]
Important Announcement: Closure of GitHub Repository Issues, Website Redesign, and Discord Channel Invitation
We apologize for the inconvenience caused, but we must inform you that all current issues in our repository will be closed. This decision aims to improve our development process and enhance organization.

Excitingly, we are announcing a complete redesign of our website, focused on improving user experience and incorporating new features aligned with our goals.

Please note that approximately half of the existing issues are redundant and will be closed accordingly.

We also invite you to join our Discord channel for project collaboration and communication. Visit GSSoC server and assign yourself Web Resource Hub project role using the self-roles feature.

[Join here](https://discord.com/channels/1099745007172329592/1110637817383632957)

Your feedback and support are invaluable to us. We look forward to hearing your thoughts on the upcoming changes.

Thank you for your understanding and continued support.

Sincerely,
Project Admin
