### ISSUE TITLE
[STYLE] Make the card.jsx more responsive

### ISSUE THREAD

**Issue by Preetam078** [jayk-gupta/web-resources-project#130]
I have observed that the information Card in the project is not responsive across different screen size.

![Screenshot from 2023-05-22 20-54-29](https://github.com/jayk-gupta/web-resources-project/assets/81969353/7065b5b6-979d-40ff-8f29-556397a20851)

I want to make this card responsive in GSSOC 2023 
please assign this issue to me.

**Comment by jayk-gupta** [comment]
This issue is already being raised
