### ISSUE TITLE
[STYLE] Want to add a footer 

### ISSUE THREAD

**Issue by Soumyajit2825** [jayk-gupta/web-resources-project#135]
I want to add a footer section 
It will be more beautiful if there we can add a footer section under the website

Adding a responsive footer which will be responsive for all the devices
![Screenshot 2023-05-23 010257](https://github.com/jayk-gupta/web-resources-project/assets/100519291/33fcc04c-44bd-4c22-b59c-6b7e152bb970)

Please let me know if I can do this task
Thank You

**Comment by jayk-gupta** [comment]
Yes, you can work on it!

**Comment by Soumyajit2825** [comment]
Thanks @jayk-gupta I will do it within tomorrow

**Comment by Soumyajit2825** [comment]
@jayk-gupta Is it ok?

![Screenshot 2023-05-24 233940](https://github.com/jayk-gupta/web-resources-project/assets/100519291/5f00613a-1b98-429f-9318-58c0b400dd81)
You can suggest me if you want something else in this
