### ISSUE TITLE
ISSUE : Tool Section

### ISSUE THREAD

**Issue by Soumyajit2825** [jayk-gupta/web-resources-project#136]
**Tool Section Update**
I want to add some ai tools in the tool section which will really help developers in web developing

**AI Tools as a Web Dev Resource**
**ChatGPT/Uizard.Io/Sketch2Code/GitHub Copilot/Postcards AI/Beautiful AI/Bard AI/Durable AI/Blackbox AI and many more** 

**I want to add these ai tools in the resource section as a card component** 

**There are various websites for these respecting ai tools I will add it on the web page**

**Topic or Category**
Specify the topic or category that best represents the subject matter of the resource.

**Intended Audience : Beginner , Intermediate and Advanced all kind of developers need these ai tools as a helper**

**Checklist (optional)**
- [ ] I have conducted a search to ensure this resource is not a duplicate.
- [ ] I confirm that this resource complies with the guidelines and policies of the project/repository.

**Comment by jayk-gupta** [comment]
# Important Announcement: Closure of GitHub Repository Issues, Website Redesign, and Discord Channel Invitation
We apologize for the inconvenience caused, but we must inform you that all current issues in our repository will be closed. This decision aims to improve our development process and enhance organization.

Excitingly, we are announcing a complete redesign of our website, focused on improving user experience and incorporating new features aligned with our goals.

Please note that approximately half of the existing issues are redundant and will be closed accordingly.

We also invite you to join our Discord channel for project collaboration and communication. Visit GSSoC server and assign yourself Web Resource Hub project role using the self-roles feature.

[Join here](https://discord.com/channels/1099745007172329592/1110637817383632957)

Your feedback and support are invaluable to us. We look forward to hearing your thoughts on the upcoming changes.

Thank you for your understanding and continued support.

Sincerely,
Project Admin
