### ISSUE TITLE
Redundant Code and Components for Each Section

### ISSUE THREAD

**Issue by MaheshMoholkar** [jayk-gupta/web-resources-project#140]
Problem -
I noticed that there is a lot of redundant code and components in the project, specifically the HtmlC.jsx, cssB.jsx, javascript.jsx, and React.jsx files. These components are essentially performing the same functionality for different sections with different data.

Solution - 
To address these issues and improve code organization, I suggest creating a more reusable and dynamic component that can replace the redundant code. This component will take data dynamically and render the section content accordingly.

**Comment by jayk-gupta** [comment]
Yes, you can do that

**Comment by jayk-gupta** [comment]
# Important Announcement: Closure of GitHub Repository Issues, Website Redesign, and Discord Channel Invitation
We apologize for the inconvenience caused, but we must inform you that all current issues in our repository will be closed. This decision aims to improve our development process and enhance organization.

Excitingly, we are announcing a complete redesign of our website, focused on improving user experience and incorporating new features aligned with our goals.

Please note that approximately half of the existing issues are redundant and will be closed accordingly.

We also invite you to join our Discord channel for project collaboration and communication. Visit GSSoC server and assign yourself Web Resource Hub project role using the self-roles feature.

[Join here](https://discord.com/channels/1099745007172329592/1110637817383632957)

Your feedback and support are invaluable to us. We look forward to hearing your thoughts on the upcoming changes.

Thank you for your understanding and continued support.

Sincerely,
Project Admin
