### ISSUE TITLE
[STYLE] Want to make a Dark / Light mode Button

### ISSUE THREAD

**Issue by Abhishek8287** [jayk-gupta/web-resources-project#150]
Is your feature request related to a problem? Please describe.

When you use the screen for a long time it is not good for your eyes. This will affect your eyes and lead to serious problems.
Some people also don't like bright colors and find it depressing that this will reduce user retention on the website.

Describe the solution you'd like

I want to increase user retention for the website and provide users with a pleasant experience using our website.
I want to create a choice for them the way they want to use the website, be it in dark mode or night mode.

Describe alternatives you've considered

I would like to build a dark and light mode button for the website .on clicking which the theme of the website get change .

Additional context
I want to know do u have any special color theme for the dark mode if any please let me know .

Please assign me this issue I would like to work on this issue under GSSOC'23

**Comment by jayk-gupta** [comment]
Already assigned to someone!
