### ISSUE TITLE
[ADD] React websites in the website section

### ISSUE THREAD

**Issue by jayk-gupta** [jayk-gupta/web-resources-project#155]
**Issue Description**
Add more React websites to learn react in the website section

**Comment by Jennifer-tech** [comment]
i will like to claim this issue

**Comment by ashutoshgithubs** [comment]
@jayk-gupta I want to add more resources

**Comment by Soumya1219** [comment]
@jayk-gupta Kindly assign me with this issue :)

**Comment by Isha988** [comment]
@jayk-gupta I want to work on this issue. Would you please assign it to me.
