### ISSUE TITLE
[FEAT] Adding games to improve web dev and programming skills

### ISSUE THREAD

**Issue by nishita2104** [jayk-gupta/web-resources-project#158]
**Is your feature request related to a problem? Please describe.**
Learning web dev and programming concepts can be boring at times. We could use a productive break from reading a lot of documentation and watching videos on end.

**Describe the solution you'd like**
Games always make learning concepts easier. So, to learn web dev or even general programming games can be highly beneficial like FLEXBOX FROGGY http://flexboxfroggy.com/ or CODE COMBAT http://codecombat.com/.

**Describe alternatives you've considered**
Videos can be an alternative but games make it more interesting. 

**Additional context**
So adding a Games section would prove helpful for all the budding amateur developers out there. 
Please assign this issue to me under GSSoC'23.

**Comment by jayk-gupta** [comment]
You can add them in the challenges sections.
flexboxfroggy can be added under CSS tag.
