### ISSUE TITLE
[Addition] Add more resources

### ISSUE THREAD

**Issue by jayk-gupta** [jayk-gupta/web-resources-project#16]
Add more resources in whichever section you would like to add

**Comment by bkrayaguru931** [comment]
I want to work on it under gssoc'23. Could you please assign this issue to me.

**Comment by yashpreet2707** [comment]
Even I'd like to add one resource in the tools section. Please assign this to me.

**Comment by urz-ahmed** [comment]
Dear jayk-gupta,
I would like to add some curated resources whichever I know my best.
Pease assign me this issue under gssoc'23.

**Comment by jayk-gupta** [comment]
Create a issue and mention in which section you want to add resources and also if possible what resource, I will assign it respectively.

**Comment by urz-ahmed** [comment]
ok I want to add one more section of AI & Machine Learning which will be curated with blogs, courses(paid and unpaid also) and some websites that can help students to get started in the AI & ML field.
Please assign me this issue under gssoc'2023 that I can work on this.

**Comment by bkrayaguru931** [comment]
I want to add one more JavaScript book that presents concepts using visual aids to enhance understanding and some css tools that have significantly streamlined my workflow. 
Kindly assign me this issue under GSSoC'23.

**Comment by Geeta259** [comment]
I would like to add more resources into a website section.
In this section add some cards with contains various popular websites Names , Images , Links and short description . To click on this link user can get more information about Navbar links modules and other also.

I want to contribute on this project under GSSoC' 23.
Please assign this to me !

**Comment by lalitkumawat1m** [comment]
I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.
