### ISSUE TITLE
[STYLE]Want to Fix Sidebar of the website

### ISSUE THREAD

**Issue by piyush-mahajan** [jayk-gupta/web-resources-project#176]
sidebar of the website is not consistent with the design and also it is not responsive so i want to fix the styling issue as i have worked on these type of things in past projects
![wedreso](https://github.com/jayk-gupta/web-resources-project/assets/98900169/067e158b-bce3-4d3b-abda-24b2ac43d92b)
can you assign this to me🙂

**Comment by jayk-gupta** [comment]
Yes, you can work on it.
Read the readme file and contribution guidelines file.
Make a PR to dev branch!
