### ISSUE TITLE
Addition of New Resources

### ISSUE THREAD

**Issue by bkrayaguru931** [jayk-gupta/web-resources-project#18]
I want to add one more JavaScript book that presents concepts using visual aids to enhance understanding, some css tools that have significantly streamlined my workflow and some videos in JavaScript and React.

Also another idea is to add one more section for DSA ( Videos, Websites, Challenges, Books, Tools ). I have a few fantastic resources that I find extremely valuable. I'm hopeful that my proposal will be accepted, and I'll be given the opportunity to work on this issue under GSSoC'23.

**Comment by jayk-gupta** [comment]
Actually the project is about web resources, so you can add those only.
You can add more websites, videos etc for js, react etc.
I am thinking to add  design inspiration sites and tools so you can add that also, I will create an issue.

**Comment by bkrayaguru931** [comment]
Yeah it's a great idea to add design inspiration component. I would like to work on that. Kindly assign me.

**Comment by bkrayaguru931** [comment]
> Actually the project is about web resources, so you can add those only. You can add more websites, videos etc for js, react etc. I am thinking to add design inspiration sites and tools so you can add that also, I will create an issue.

Kindly assign me this issue so that I can add more valuable resources under css, js and react

**Comment by jayk-gupta** [comment]
Okay, I will create separate issues for each and then assign you.

**Comment by bkrayaguru931** [comment]
Hey! I'm really excited to contribute and would appreciate it if you could assign me.
