### ISSUE TITLE
Book addition : Learning REACT

### ISSUE THREAD

**Issue by Abhinavcode13** [jayk-gupta/web-resources-project#183]
**Issue Description**
I want to add a book based on react.js which is used in front end development.

**Resource Details**
**Resource Type:** Book
**Title/Name of the Resource:** Learning React  
**Description:** 
Learning React: Modern Patterns for Developing React Apps" is a comprehensive guide that introduces you to the world of React and equips you with the skills to build robust and efficient web applications. The book covers the fundamentals of React, including components, JSX, and state management. It also explores advanced concepts such as React hooks, context, and Redux for managing application state.

**URL or Source:** 
file:///C:/Users/Abhinav%20Kumar/Downloads/Alex_Banks_and_Eve_Porcello-Learning_React-EN.pdf

**Topic or Category**
React - Front end development

**Intended Audience (optional)**
Beginner to advance

**Benefits of Adding this Resource**
Comprehensive coverage
Structured learning path
Practical examples and projects
In-depth explanations and insights
Reference material

**Checklist (optional)**
- [✔️ ] I have conducted a search to ensure this resource is not a duplicate.
- [✔️ ] I confirm that this resource complies with the guidelines and policies of the project/repository.

**Comment by jayk-gupta** [comment]
Yes, you can add it.
Read the readme file and contribution guidelines file.
Also you can watch the video to add new resources.
Make a PR to dev branch!
