### ISSUE TITLE
Adding new resources to CSS and JS section.

### ISSUE THREAD

**Issue by Atharva-3000** [jayk-gupta/web-resources-project#184]
**Issue Description**
Please provide a clear and concise description of the resource you would like to add, including the topic or category it pertains to.
Adding a new YouTube channel called Hyperplexed for CSS and JS.
**Resource Details**
**Resource Type:** Video 
**Title/Name of the Resource:** Hyperplexed  
**Description:** The channel Hyperplexed reached web development in a very intuitive way by redesigning mainstream stuff.  
**URL or Source:** https://www.youtube.com/@Hyperplexed

**Topic or Category**
Videos: CSS & JS

**Intended Audience (optional)**
Who is the intended audience for this resource?
Intermediate users

**Benefits of Adding this Resource**
Learning faster and more efficiently by redesigning things in a better way with more emphasis on design and functionality.

**Checklist (optional)**
- [x] I have conducted a search to ensure this resource is not a duplicate.
- [x] I confirm that this resource complies with the guidelines and policies of the project/repository.

![Hyperplexed](https://github.com/jayk-gupta/web-resources-project/assets/72994819/9836c8bb-ae76-4cc1-b648-b1f9dee2efb7)

**Comment by jayk-gupta** [comment]
Read the readme file and contribution guidelines file.
And then make a PR to dev branch!
