### ISSUE TITLE
[GSSoC '23] Addition of best REACT website for programmers

### ISSUE THREAD

**Issue by Abhinavcode13** [jayk-gupta/web-resources-project#186]
**Issue Description**
To add a website which can be used as a learning source for react.

**Resource Details**
**Resource Type:** Website  
**Title/Name of the Resource:**  Alterclass
**Description:** 
The [React Fundamentals course](https://www.alterclass.io/courses/react?ref=5ef9b5f324fba57c45713ca0) on Alterclass is completely FREE and good enough to learn the basics of React.js frameworks like props, state management, and JSX.
**URL or Source:** [Provide the link to the resource or mention the source]
https://alterclass.io/courses/build-a-fullstack-app-with-nextjs-supabase-and-prisma-322389284337222224

**Topic or Category**
Website -to learn REACT 

**Intended Audience (optional)**
Beginners friendly

**Benefits of Adding this Resource**
The course is taught by Greg D'Angelo, a senior software engineer and mentor specializing in teaching React, JavaScript and much more. He has been working with React, Node, and MongoDB for the last few years to build large-scale production applications in a wide range of industries hence it is more beneficial for all age gropus

.

**Checklist (optional)**
- [✔️ ] I have conducted a search to ensure this resource is not a duplicate.
- [✔️ ] I confirm that this resource complies with the guidelines and policies of the project/repository.

Please assign me this @jayk-gupta under gssoc 23

**Comment by jayk-gupta** [comment]
# Important Announcement: Closure of GitHub Repository Issues, Website Redesign, and Discord Channel Invitation
We apologize for the inconvenience caused, but we must inform you that all current issues in our repository will be closed. This decision aims to improve our development process and enhance organization.

Excitingly, we are announcing a complete redesign of our website, focused on improving user experience and incorporating new features aligned with our goals.

Please note that approximately half of the existing issues are redundant and will be closed accordingly.

We also invite you to join our Discord channel for project collaboration and communication. Visit GSSoC server and assign yourself Web Resource Hub project role using the self-roles feature.

[Join here](https://discord.com/channels/1099745007172329592/1110637817383632957)

Your feedback and support are invaluable to us. We look forward to hearing your thoughts on the upcoming changes.

Thank you for your understanding and continued support.

Sincerely,
Project Admin
