### ISSUE TITLE
Addition of More React Learning Tools (It contains only one till now)

### ISSUE THREAD

**Issue by sangdeepganvir** [jayk-gupta/web-resources-project#187]
**Issue Description**
I want to add a React Learning Tool  **React Icons** (React Icons is a library of free and customizable icons for React applications.)

**Resource Details**
**Resource Type:** Tools
**Title/Name of the Resource:**  React Icons 

**Description:** 
React Icons : By using React Icons, developers can easily incorporate icons into their React projects without the need for separate icon files or additional dependencies. The icons are available as React components, allowing them to be easily imported and used directly in the code. React Icons simplifies the process of including high-quality icons in React projects, saving developers time and effort.

**URL or Source:** https://react-icons.github.io/react-icons/

**Topic or Category**
Tools -> React

**Intended Audience (optional)**
It caters to developers of all levels, providing a simple API and customization options to enhance the visual appeal and functionality of React projects.

**Benefits of Adding this Resource**
React Icons is valuable to users as it simplifies icon integration, offers customization options, and provides a diverse collection of icons for React applications. For contributors, it offers opportunities for skill development, collaboration, and making an impact in the React community.
.

**Comment by jayk-gupta** [comment]
# Important Announcement: Closure of GitHub Repository Issues, Website Redesign, and Discord Channel Invitation
We apologize for the inconvenience caused, but we must inform you that all current issues in our repository will be closed. This decision aims to improve our development process and enhance organization.

Excitingly, we are announcing a complete redesign of our website, focused on improving user experience and incorporating new features aligned with our goals.

Please note that approximately half of the existing issues are redundant and will be closed accordingly.

We also invite you to join our Discord channel for project collaboration and communication. Visit GSSoC server and assign yourself Web Resource Hub project role using the self-roles feature.

[Join here](https://discord.com/channels/1099745007172329592/1110637817383632957)

Your feedback and support are invaluable to us. We look forward to hearing your thoughts on the upcoming changes.

Thank you for your understanding and continued support.

Sincerely,
Project Admin
