### ISSUE TITLE
Addition of new section and resources

### ISSUE THREAD

**Issue by urz-ahmed** [jayk-gupta/web-resources-project#19]
I want to add one more section of AI & Machine Learning which will be curated with 
blogs, courses (paid and unpaid also) and some websites that can help students to get started in the AI & ML field.
Please assign me this issue under gssoc'2023 that I can work on this.
I would love to on this issue.

**Comment by jayk-gupta** [comment]
The project is for web resources so how can we add AI and ML?
First I need to cover web resources completely.

**Comment by urz-ahmed** [comment]
ok I can add that also.
What about web3.0 it is trending as well
I can add different sections of web3 that as follows:
1) Websites
2) Channels
3) Repos
4) Courses
Additionally I can add database resources that is needed in web and its categories like above.
Assign me this issue under gssoc'23 so I can work on this project.

**Comment by jayk-gupta** [comment]
No web3 for now, first we need to cover web2 resources

**Comment by jayk-gupta** [comment]
Important Announcement: Closure of GitHub Repository Issues, Website Redesign, and Discord Channel Invitation
We apologize for the inconvenience caused, but we must inform you that all current issues in our repository will be closed. This decision aims to improve our development process and enhance organization.

Excitingly, we are announcing a complete redesign of our website, focused on improving user experience and incorporating new features aligned with our goals.

Please note that approximately half of the existing issues are redundant and will be closed accordingly.

We also invite you to join our Discord channel for project collaboration and communication. Visit GSSoC server and assign yourself Web Resource Hub project role using the self-roles feature.

[Join here](https://discord.com/channels/1099745007172329592/1110637817383632957)

Your feedback and support are invaluable to us. We look forward to hearing your thoughts on the upcoming changes.

Thank you for your understanding and continued support.

Sincerely,
Project Admin
