### ISSUE TITLE
[STYLE]Text Alignment Issue on Front Page

### ISSUE THREAD

**Issue by Dneth04** [jayk-gupta/web-resources-project#190]
Problem Description: In the current state of the website's front page, there is a text alignment issue that leads to frustration and a lack of visual coherence. The text appears misaligned, which creates inconsistency and hampers readability. This problem can be off-putting to users and detracts from the overall user experience.

Solution Description: I would like to address the text alignment issue on the website's front page by implementing a solution that combines both CSS and HTML modifications. The scroll should be removed, and we should bring all the details in proper alignment so that it can correctly fit into the front page.
Alternative: Without a Scroll may a footer to the page can also be added!!

<img width="926" alt="Front pg issue" src="https://github.com/jayk-gupta/web-resources-project/assets/112483364/c6639461-532d-4d98-ba3b-5e99d5821be7">

**Comment by jayk-gupta** [comment]
# Important Announcement: Closure of GitHub Repository Issues, Website Redesign, and Discord Channel Invitation
We apologize for the inconvenience caused, but we must inform you that all current issues in our repository will be closed. This decision aims to improve our development process and enhance organization.

Excitingly, we are announcing a complete redesign of our website, focused on improving user experience and incorporating new features aligned with our goals.

Please note that approximately half of the existing issues are redundant and will be closed accordingly.

We also invite you to join our Discord channel for project collaboration and communication. Visit GSSoC server and assign yourself Web Resource Hub project role using the self-roles feature.

[Join here](https://discord.com/channels/1099745007172329592/1110637817383632957)

Your feedback and support are invaluable to us. We look forward to hearing your thoughts on the upcoming changes.

Thank you for your understanding and continued support.

Sincerely,
Project Admin
