### ISSUE TITLE
Make the Website Responsive.

### ISSUE THREAD

**Issue by MohnishK7** [jayk-gupta/web-resources-project#20]
Hi @jayk-gupta, hope you are doing well, I have been practicing frontend for a long time and if you assign this task to me, I'd be grateful.
I will ensure that it adapts and displays properly on different devices and screen sizes, such as desktops, tablets, and smartphones. Here are some steps you can follow to make your website responsive:

**Use a responsive framework or CSS grid system:** Frameworks like Bootstrap or CSS grid systems provide pre-built responsive layouts and components that can make your website responsive more easily. They offer grid structures and responsive classes that can automatically adjust the layout based on the screen size.

**Implement a mobile-first approach:** Start by designing and coding your website for mobile devices first and then progressively enhance it for larger screens. This approach ensures that your website is optimized for small screens and then adapts to larger ones.

**Use media queries:** Media queries allow you to apply different styles based on the screen size or device. By using CSS media queries, you can define specific styles for different breakpoints (e.g., small screens, tablets, desktops) and adjust the layout and content accordingly.

Under GSSOC 23

**Comment by jayk-gupta** [comment]
Have you learnt tailwindcss?
The same is used in the project

**Comment by lalitkumawat1m** [comment]
I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.

**Comment by Jyotipal29** [comment]
I'm interested in working on this issue as I have recent experience with Tailwind CSS. I believe I'm a great fit for this task. Please assign it to me

**Comment by jayk-gupta** [comment]
This issue is already raised, so please see the issues before creating one.
