### ISSUE TITLE
[STYLE] Create attractive hover animation on tags

### ISSUE THREAD

**Issue by prrockzed** [jayk-gupta/web-resources-project#205]
Is your feature request related to a problem? Please describe.
I will create hover animation on the tabs HTML, CSS, Javascript and ReactJS

Describe the solution you'd like
It will be CSS animation and will be attractive. Once done I will share the screenshots with you.

<img width="726" alt="prrockzed 2023-05-25 at 11 58 47 AM" src="https://github.com/jayk-gupta/web-resources-project/assets/97661506/245325a3-cc48-4868-8c00-2c6e57ea3f46">

Additional context
@jayk-gupta please assign this style feature to me under GSSoC'23

**Comment by jayk-gupta** [comment]
# Important Announcement: Closure of GitHub Repository Issues, Website Redesign, and Discord Channel Invitation
We apologize for the inconvenience caused, but we must inform you that all current issues in our repository will be closed. This decision aims to improve our development process and enhance organization.

Excitingly, we are announcing a complete redesign of our website, focused on improving user experience and incorporating new features aligned with our goals.

Please note that approximately half of the existing issues are redundant and will be closed accordingly.

We also invite you to join our Discord channel for project collaboration and communication. Visit GSSoC server and assign yourself Web Resource Hub project role using the self-roles feature.

[Join here](https://discord.com/channels/1099745007172329592/1110637817383632957)

Your feedback and support are invaluable to us. We look forward to hearing your thoughts on the upcoming changes.

Thank you for your understanding and continued support.

Sincerely,
Project Admin
