### ISSUE TITLE
[FEAT][GSSoC'23] Adding a 'get started' page 

### ISSUE THREAD

**Issue by heyysiri** [jayk-gupta/web-resources-project#212]
**Is your feature request related to a problem? Please describe.**
When users open the website, they see multiple resources on the nav bar such as tools, videos, websites, etc. Sometimes they may get confused as to what to go through first.

**Describe the solution you'd like**
Adding a 'get started' button on the homepage which will direct them to a page that will provide links to the resources separately with added descriptions on the people's preference on their type of learning(ex. visually-videos, by reading-websites, etc) will benefit the users.

This was what I was trying to convey in #206 
I would like to work on this. Please assign me this issue under gssoc'23.

**Comment by jayk-gupta** [comment]
# Important Announcement: Closure of GitHub Repository Issues, Website Redesign, and Discord Channel Invitation
We apologize for the inconvenience caused, but we must inform you that all current issues in our repository will be closed. This decision aims to improve our development process and enhance organization.

Excitingly, we are announcing a complete redesign of our website, focused on improving user experience and incorporating new features aligned with our goals.

Please note that approximately half of the existing issues are redundant and will be closed accordingly.

We also invite you to join our Discord channel for project collaboration and communication. Visit GSSoC server and assign yourself Web Resource Hub project role using the self-roles feature.

[Join here](https://discord.com/channels/1099745007172329592/1110637817383632957)

Your feedback and support are invaluable to us. We look forward to hearing your thoughts on the upcoming changes.

Thank you for your understanding and continued support.

Sincerely,
Project Admin
