### ISSUE TITLE
[STYLE] Alignment Issue: Books Component Welcome Text not Centered

### ISSUE THREAD

**Issue by mhdamaan79** [jayk-gupta/web-resources-project#22]
The welcome text for the book component is positioned above the center, whereas all other components have their welcome text centered. This misalignment affects the visual consistency of the website and should be corrected to ensure uniformity in the positioning of welcome text across all components.

I would like to work on it under **gssoc'23.**

![Others](https://github.com/jayk-gupta/web-resources-project/assets/118375524/54910279-f4e3-43bd-b60a-e3e4232990ad)
![Books ( Issue )](https://github.com/jayk-gupta/web-resources-project/assets/118375524/8ecf8730-de33-4c30-bd28-0a7eea22265d)

**Comment by jayk-gupta** [comment]
Yes, it is there!
Someone has already raised same issue before.

**Comment by mhdamaan79** [comment]
So, Can I work on this issue? @jayk-gupta
