### ISSUE TITLE
New Resource For JS Section.

### ISSUE THREAD

**Issue by tayyab-ilyas** [jayk-gupta/web-resources-project#226]
**Issue Description**
Adding the YouTube playlist of Jonas Schmedtmann to the JS section.

**Resource Details**
**Resource Type:** Video
**Title/Name of the Resource:** [Enter the title or name]  
**Description:** A free JavaScript mini course by Jonas Schmedtmann
**URL or Source:** https://www.youtube.com/playlist?list=PLvtRgUbhWmy8MCUNDT2hiI0jpGgjTfSLE

**Topic or Category**
JavaScript
**Intended Audience (optional)**
Beginners

**Benefits of Adding this Resource**
Super Valuable for people getting started with JS

**Checklist (optional)**
- [x] I have conducted a search to ensure this resource is not a duplicate.
- [x] I confirm that this resource complies with the guidelines and policies of the project/repository.
<img width="904" alt="jonasch_js" src="https://github.com/jayk-gupta/web-resources-project/assets/110786036/710f13cf-a48e-4563-a405-836f5a98450c">

**Comment by jayk-gupta** [comment]
# Important Announcement: Closure of GitHub Repository Issues, Website Redesign, and Discord Channel Invitation
We apologize for the inconvenience caused, but we must inform you that all current issues in our repository will be closed. This decision aims to improve our development process and enhance organization.

Excitingly, we are announcing a complete redesign of our website, focused on improving user experience and incorporating new features aligned with our goals.

Please note that approximately half of the existing issues are redundant and will be closed accordingly.

We also invite you to join our Discord channel for project collaboration and communication. Visit GSSoC server and assign yourself Web Resource Hub project role using the self-roles feature.

[Join here](https://discord.com/channels/1099745007172329592/1110637817383632957)

Your feedback and support are invaluable to us. We look forward to hearing your thoughts on the upcoming changes.

Thank you for your understanding and continued support.

Sincerely,
Project Admin
