### ISSUE TITLE
Create a sign in option

### ISSUE THREAD

**Issue by KhushiKhandelwal610** [jayk-gupta/web-resources-project#23]
A sign in and log in option can be created for the users so that whenever they open this website for resources , they have the idea what they were learning earlier and then they can start from that point. Basically that will create a profile page for the user that show the users' previous interaction with the website. They can add the desired books to the wishlist etc.

I am the contributor in GSSOC,23.
I would like to work on this issue. Please assign me to it.

**Comment by jayk-gupta** [comment]
Yeah, I have thought of it.
How will you implement this?

**Comment by KhushiKhandelwal610** [comment]
I can create the UI for sign in/log in page that leads to user information and setting where we can add user profile,  wishlist, also a option for community, settings, history, log out etc. I think it would be great if the idea of creating a community can be created as it would be helpful to interact with other users of having knowledge of same as well as different technology .

**Comment by jayk-gupta** [comment]
What will you use to implement it? 
We need a database or local storage to store data.

**Comment by KhushiKhandelwal610** [comment]
I can only create the UI for sign in/log in page

**Comment by jayk-gupta** [comment]
ohk, we need backend for it first.
I will assign you as we add backend
