### ISSUE TITLE
Add a coupon section for various certificated online courses 

### ISSUE THREAD

**Issue by Manikantan-S** [jayk-gupta/web-resources-project#24]
**Is your feature request related to a problem? Please describe.**
Every student whoever is in college is in generally short of finances which prevent him from doing certificated courses and he generally refers the free websites .In the resources section we have a few online courses if we add more related courses and also take the coupon codes from twitter or various websites we can ensure that the user can do certificated courses for a cheap price 

**Describe the solution you'd like**
I would like to add a coupon section in the bar which would display the top courses related to his or her field of study in a particular website along with the latest discount coupon codes that are applicable to that particular course

**Describe alternatives you've considered**
In my websites they allow financial aid for the course. Many students don't know what to write there and often it is rejected .We can give them a platform where students get their aid answers checked by us and we suggest some improvements there

The tech stack will be HTML,CSS,React JS. We will be using web scraping to retrieve the coupon codes
 
Please assign this issue to me under GSSOC'23 .I am interested to work on this project @jayk-gupta

**Comment by jayk-gupta** [comment]
The project is of web resources, so I don't think so we should add coupon in it.
