### ISSUE TITLE
[BUG] Double Navigation for Homepage

### ISSUE THREAD

**Issue by arpitghura** [jayk-gupta/web-resources-project#240]
**Describe the bug**
The Navigation for reaching homepage is given twice. 
1. We can simply go to home page using logo
2. By using Home link in menu

**Expected behavior**
A single homepage button is there like only with the help of Logo.

**Screenshots**
![image](https://github.com/jayk-gupta/web-resources-project/assets/41796013/15c647b8-3fe5-40e0-975b-2a5ca3d8d2e7)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by jayk-gupta** [comment]
we are re-designing it!
