### ISSUE TITLE
[Add] New CSS Resource

### ISSUE THREAD

**Issue by Shiva-Sai-ssb** [jayk-gupta/web-resources-project#241]
**Issue Description**
Please provide a clear and concise description of the resource you would like to add, including the topic or category it pertains to.

**Resource Details**
**Resource Type:** Video 
**Title/Name of the Resource:** Dave Gray CSS Playlist  
**Description:** This comprehensive playlist serves as a complete guide for any aspiring web developer who wants to learn and master CSS.
**URL or Source:** https://www.youtube.com/playlist?list=PL0Zuz27SZ-6Mx9fd9elt80G1bPcySmWit

**Topic or Category**
Youtube - Learning CSS

**Intended Audience (optional)**
Who is the intended audience for this resource? (e.g., beginners, intermediate, advanced, researchers)

**Benefits of Adding this Resource**
Explain how this resource would be valuable to users and contributors of the project/repository.

**Additional Information (optional)**
Include any additional information or context that might be helpful for evaluating the resource or understanding its relevance.

**Checklist (optional)**
- [x] I have conducted a search to ensure this resource is not a duplicate.
- [x] I confirm that this resource complies with the guidelines and policies of the project/repository.

**Comment by KHADIJA-09** [comment]
@jayk-gupta please assign me this problem to solve.

**Comment by jayk-gupta** [comment]
assigned

**Comment by KHADIJA-09** [comment]
Thanks a lot

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by KHADIJA-09** [comment]
Hello sir! There is some issue I am facing.
pnpm dev command is not running properly actually I have checked in the package.json file and under script tag dev tag existing but after that I am not able to run the program on local system.
Disclaimer - The information contained in this electronic communication is intended solely for the individual(s) or entity to which it is addressed. It may contain proprietary, confidential and/or legally privileged information. Any review, retransmission, dissemination, printing, copying or other use of, or taking any action in reliance on the contents of this information by person(s) or entities other than the intended recipient is strictly prohibited and may be unlawful. If you have received this communication in error, please notify us by responding to this email or telephone and immediately and permanently delete all copies of this message and any attachments from your system(s). The contents of this message do not necessarily represent the views or policies of ABES.
