### ISSUE TITLE
[STYLE] Responsiveness of Home page

### ISSUE THREAD

**Issue by Monishka8303** [jayk-gupta/web-resources-project#242]
Is your feature request related to a problem? Please describe.
The responsiveness of the homepage is a bit off. At 1024px (Laptop view), the text is overflowing, and in mobile view, the image is really small and the svg is in the middle.

Describe the solution you'd like
I would like to hide the image and move the svg to bottom of the page  in mobile view. Also, I would like to reduce the font-size of the content in the mobile view and laptop view(1024px) so that it fits perfectly.

Additional context
I'm in GSSoC'23.

![Screenshot](https://github.com/jayk-gupta/web-resources-project/assets/115769741/8fd1f2d6-7223-4d14-95f9-8d55a21da0eb)

![Screenshot (172)](https://github.com/jayk-gupta/web-resources-project/assets/115769741/ed3b6f58-32f9-4181-9b84-43ea8f18a773)

**Comment by jayk-gupta** [comment]
Site is being redesigned!

**Comment by jayk-gupta** [comment]
Would you like to work on it?

**Comment by Monishka8303** [comment]
Sure!

**Comment by Monishka8303** [comment]
I'm a bit confused. I did create a new branch with the name "monishka" and did all the changes in my forked repository, and created the PR . Do I need to do anything else?

**Comment by KHADIJA-09** [comment]
@Monishka8303 please assign me this problem.
