### ISSUE TITLE
Adding 404 error page [FEAT]

### ISSUE THREAD

**Issue by SagarPatil007** [jayk-gupta/web-resources-project#243]
I want to add 404 error page 
can you please assign me this role @jayk-gupta .

**Comment by jayk-gupta** [comment]
Yes, just wait !
I will give colors and font

**Comment by Deepanshu0703** [comment]
If this issue is still available then i can work on it

**Comment by PatilHarshh** [comment]
hey @jayk-gupta i am intrested to work on it 
![Screenshot (76)](https://github.com/jayk-gupta/web-resources-project/assets/120102234/9ce915eb-3dc8-4cfb-b668-e6848797be55)
![Screenshot (73)](https://github.com/jayk-gupta/web-resources-project/assets/120102234/67cbf721-fef8-405f-89e6-401bd1728719)

**Comment by jayk-gupta** [comment]
working on it?
