### ISSUE TITLE
[STYLE]

### ISSUE THREAD

**Issue by Soumyajit2825** [jayk-gupta/web-resources-project#247]
Creating a footer for this website 
You've already assigned me in this issue previously @jayk-gupta 
I have done the changes already in my desktop
Please assign me to make a PR
![Screenshot 2023-05-24 233940](https://github.com/jayk-gupta/web-resources-project/assets/100519291/c3372c39-1a91-49a0-a786-7c6d47bfc192)

**Comment by jayk-gupta** [comment]
Actually the theme is being changed, so make according to the.
We will provide color scheme and font!

**Comment by Soumyajit2825** [comment]
@jayk-gupta Ok provide me the color scheme and font please

**Comment by jayk-gupta** [comment]
Yes

**Comment by Soumyajit2825** [comment]
@jayk-gupta any color scheme or font?
