### ISSUE TITLE
[BUG]: Card Alignment and Layout Issues Causing Wasted Space

### ISSUE THREAD

**Issue by itsme-shivamkumar** [jayk-gupta/web-resources-project#249]
## Description of the bug
The cards in the website are not aligned properly and lack a good layout, resulting in leftout unused space.

## To Reproduce

- Go to the website.
- Click on the "Videos" link.
- Click on the "Website" link.
- Click on the "Challenges" link.
- Observe the card alignment and layout issues, with unused space.
- Expected behavior
- The cards should be properly aligned and have a well-designed layout, without any wasted space.

## Before:

https://github.com/jayk-gupta/web-resources-project/assets/91745441/47c4d1cd-323b-4aae-acc6-ab8fa0d695f1

## After:

https://github.com/jayk-gupta/web-resources-project/assets/91745441/957b2c94-73a8-452f-ba7b-df992bb9eede

### Desktop (please complete the following information):
OS: [Windows 10]
Browser: [Chrome, Firefox, Brave]

## Additional context
The issue can be easily observed by visiting the website and clicking on the "Videos," "Website," "Challenges," and other relevant links. The problem persists across different sections of the website.

**Comment by jayk-gupta** [comment]
Website is being re-designed, so it will be fixed.
