### ISSUE TITLE
Add Footer 

### ISSUE THREAD

**Issue by 9520prashant** [jayk-gupta/web-resources-project#27]
Footer is a very important segment of a Website so we have to add in our Website. 
hey @jayk-gupta Assign me this. I will add amazing footer

**Comment by RahulRana701** [comment]
hi @jayk-gupta I am a GSSOC 23 contributor , I would like to work on this issue...........

**Comment by ARGHYADIPROY** [comment]
I am a GSSoC'23 contributor. I can add the footer to this website. I have all the skills required.
Please assign me this issue , I want to work on this issue under the GSSoC'23.

**Comment by PiyushaGhodake** [comment]
@jayk-gupta I would like to work on this issue.Can u pls assign it to me?

**Comment by jayk-gupta** [comment]
This issue is already raised.
