### ISSUE TITLE
[Add] New JavaScript Resource

### ISSUE THREAD

**Issue by yashpreet2707** [jayk-gupta/web-resources-project#270]
**Issue Description**
Please provide a clear and concise description of the resource you would like to add, including the topic or category it pertains to.

**Resource Details**
**Resource Type:** Video  
**Title/Name of the Resource:** JavaScript Tutorials for Beginners in Hindi 
**Description:** This comprehensive playlist serves as a complete guide for any aspiring web developer who wants to learn JavaScript from our favorite Harry sir.
**URL or Source:** https://www.youtube.com/playlist?list=PLu0W_9lII9ahR1blWXxgSlL4y9iQBnLpR

**Topic or Category**
Youtube - Learning JavaScript

**Intended Audience (optional)**
Who is the intended audience for this resource? (e.g., beginners, intermediate, advanced, researchers)

**Benefits of Adding this Resource**
Explain how this resource would be valuable to users and contributors of the project/repository.

**Additional Information (optional)**
Include any additional information or context that might be helpful for evaluating the resource or understanding its relevance.

**Checklist (optional)**
- [x] I have conducted a search to ensure this resource is not a duplicate.
- [x] I confirm that this resource complies with the guidelines and policies of the project/repository.

**Comment by jayk-gupta** [comment]
Is the issue completed?
