### ISSUE TITLE
[FEAT] Adding Images

### ISSUE THREAD

**Issue by parthpathakpp1** [jayk-gupta/web-resources-project#281]
**Is your feature request related to a problem? Please describe.**
There is no image on the cards in books section . 

**Describe the solution you'd like**
I will add different images on the cars in books section . 

https://github.com/jayk-gupta/web-resources-project/assets/85991449/c554f36a-9cfd-4736-a7df-19ef7bda2ccc

**Describe alternatives you've considered**

**Additional context**

**Comment by jayk-gupta** [comment]
yes u can add!
