### ISSUE TITLE
[STYLE]Enhancing the UI of containers of every section

### ISSUE THREAD

**Issue by Mahitej28** [jayk-gupta/web-resources-project#30]
Hello! I am Mahima Churi, a proud contributor of GSSoc'23.

📌I have gone through your website and came across the containers you added for each and every section of your website.
![image](https://github.com/jayk-gupta/web-resources-project/assets/98276915/4d3a90b4-a3d3-464c-a242-3e8a72b40675)
I would like to enhance it, by adding more animations and making it more user-friendly. 
I would be doing it using tailwind css. I have worked on similar types of containers earlier, u can see my work below : 

![image](https://github.com/jayk-gupta/web-resources-project/assets/98276915/bc153ac0-e997-47cf-9391-924ba7673a8d)

📌The Web Dev Resource heading is static, I would like to make it interactive so that it redirects back again to the home page
![image](https://github.com/jayk-gupta/web-resources-project/assets/98276915/47ffda6c-6a70-4896-9a4b-438a9023766f)

📌After solving this issue I would also like to work on adding a dark theme to the website

If you think it is legit then do assign me the issue under GSSoC '23 with the level of the PR as well

**Comment by jayk-gupta** [comment]
Yeah that's a good idea.
You can work on it!
Please go through contributing guidelines.
All the best!

**Comment by Mahitej28** [comment]
Yes sure I will go ahead with it

**Comment by jayk-gupta** [comment]
Important Announcement: Closure of GitHub Repository Issues, Website Redesign, and Discord Channel Invitation
We apologize for the inconvenience caused, but we must inform you that all current issues in our repository will be closed. This decision aims to improve our development process and enhance organization.

Excitingly, we are announcing a complete redesign of our website, focused on improving user experience and incorporating new features aligned with our goals.

Please note that approximately half of the existing issues are redundant and will be closed accordingly.

We also invite you to join our Discord channel for project collaboration and communication. Visit GSSoC server and assign yourself Web Resource Hub project role using the self-roles feature.

[Join here](https://discord.com/channels/1099745007172329592/1110637817383632957)

Your feedback and support are invaluable to us. We look forward to hearing your thoughts on the upcoming changes.

Thank you for your understanding and continued support.

Sincerely,
Project Admin
