### ISSUE TITLE
[STYLE] Improving UI of Navbar and addding Animations

### ISSUE THREAD

**Issue by himanshu-03** [jayk-gupta/web-resources-project#32]
Hello!
I am Himanshu Agarwal, a proud contribtuor at GSSoC '23. I would like to the contribute to this project by enhancing the navbar with better UI and animated buttons.

Things I will be doing as of now:

- [ ] Enhancing Header and making it fit with the theme
- [ ] Adding Animated buttons with logos

@jayk-gupta If you think it is needed then do assign me the issue under GSSoC '23 with the level of the PR as well .

**Comment by jayk-gupta** [comment]
Important Announcement: Closure of GitHub Repository Issues, Website Redesign, and Discord Channel Invitation
We apologize for the inconvenience caused, but we must inform you that all current issues in our repository will be closed. This decision aims to improve our development process and enhance organization.

Excitingly, we are announcing a complete redesign of our website, focused on improving user experience and incorporating new features aligned with our goals.

Please note that approximately half of the existing issues are redundant and will be closed accordingly.

We also invite you to join our Discord channel for project collaboration and communication. Visit GSSoC server and assign yourself Web Resource Hub project role using the self-roles feature.

[Join here](https://discord.com/channels/1099745007172329592/1110637817383632957)

Your feedback and support are invaluable to us. We look forward to hearing your thoughts on the upcoming changes.

Thank you for your understanding and continued support.

Sincerely,
Project Admin
