### ISSUE TITLE
[FEAT]Adding more frontend frameworks

### ISSUE THREAD

**Issue by salted0dreams** [jayk-gupta/web-resources-project#33]
Hello!
I am Aryan Sharma, a proud contribtuor at GSSoC '23. I would like to the contribute to this project by adding  more frameworks to the site like Angular, Vue, etc.

Things I will be doing as of now:

- [ ] Adding a framework , like Angular along with its resources
- [ ] Updating links on the home page.

@jayk-gupta If you think it is needed then do assign me the issue under GSSoC '23 with the level of the PR as well .

**Comment by salted0dreams** [comment]
@jayk-gupta If you think this is worth working on, can you please assign it to me?

**Comment by jayk-gupta** [comment]
Important Announcement: Closure of GitHub Repository Issues, Website Redesign, and Discord Channel Invitation
We apologize for the inconvenience caused, but we must inform you that all current issues in our repository will be closed. This decision aims to improve our development process and enhance organization.

Excitingly, we are announcing a complete redesign of our website, focused on improving user experience and incorporating new features aligned with our goals.

Please note that approximately half of the existing issues are redundant and will be closed accordingly.

We also invite you to join our Discord channel for project collaboration and communication. Visit GSSoC server and assign yourself Web Resource Hub project role using the self-roles feature.

[Join here](https://discord.com/channels/1099745007172329592/1110637817383632957)

Your feedback and support are invaluable to us. We look forward to hearing your thoughts on the upcoming changes.

Thank you for your understanding and continued support.

Sincerely,
Project Admin
