### ISSUE TITLE
[FEAT] Add section of games and notes in the sidebar 

### ISSUE THREAD

**Issue by An525ish** [jayk-gupta/web-resources-project#34]
**Is your feature request related to a problem? Please describe.**
I want to add a short notes and games section there

**Describe the solution you'd like**
I want to add games and notes section there because it is more engaging and would be easier to go through it without getting trapped in tutorial hell loop....would help a lot to learn such tech stacks

**Describe alternatives you've considered**

**Additional context**
Even I was about to make such a website for my juniors so if we stay connected we can take this to the next level....from enhancing the design to adding resources we will do everything

**Comment by Parth-2609** [comment]
I would love to work under this issue
Kindly assign me this issue under GSSOC '23
