### ISSUE TITLE
[STYLE] Update in logo 

### ISSUE THREAD

**Issue by Niharika2608** [jayk-gupta/web-resources-project#36]
As a GSSOC'23 contributer ! I am logo designer , I would like to update a logo.  I wanted to update logo on website

**Comment by jayk-gupta** [comment]
Yeah, sure!
We can discuss about it!

**Comment by Niharika2608** [comment]
[web resources logo .zip](https://github.com/jayk-gupta/web-resources-project/files/11529705/web.resources.logo.zip)
check it out !!

**Comment by jayk-gupta** [comment]
Can you make something like as present in site?
