### ISSUE TITLE
[FEAT] Add Quiz Section 

### ISSUE THREAD

**Issue by Akshatbhardwaj15** [jayk-gupta/web-resources-project#37]
**Is your feature request related to a problem? Please describe.**
I want to add quiz section. 

**Describe the solution you'd like**
By addition of quiz section we can enchance the learning experience of the beginners. It can help them to learn various methods easily. It can include quizzes related to HTML, CSS and JAVASCRIPT. It will help the beginners to gain hand on experience on these tech stacks and understand them very easily. After that they can create their own web projects.

**Describe alternatives you've considered**
I have different ideas related to the tech stacks present on the website.

**Additional context**
Solutions of quizzes and hints will also be there. So if anyone stuck in a problem they can take help from them.

**Comment by Akshatbhardwaj15** [comment]
Please assign me, I want to work on this.

**Comment by naveeng2402** [comment]
I'm too intensed
