### ISSUE TITLE
[FEAT] Add Project Section

### ISSUE THREAD

**Issue by aditya9277** [jayk-gupta/web-resources-project#38]
**Is your feature request related to a problem? Please describe. **
Currently the website lack the practical implementations/knowledge resource section.
I want to add projects section on the website, It will have Project Tasks of the respective languages/resources.

**Describe the solution you'd like**
By addition of projects section, web development beginners can get a path to begin with after learning from the resources and gain hand on experience For example, it will have challenging beginner projects ideas that a beginner can begin with like basic portfolio website, different CSS styling projects etc. 
Basically by projects section, a learner can get a path to implement his knowledge that he/she has gained. As making projects is equally important while learning.

**Describe alternatives you've considered**
 i can contribute to existing resources like websites, i know pretty number of underrated websites that can be added as a resource. These websites are not into the light much but are kind of goldmines.

**Additional context**
Many beginners don't know a path and what projects to be done after learning, this feature will be a great addition to the website and its resource. Solution/Links for the codes of projects will also be there, so if a learner get stuck, he can get a idea/solutions.

**Comment by aditya9277** [comment]
I am a GSSoC 23 contributor, i have already planned the implementation, and i already have a collection of suitable resources for the PROJECTS feature. Can you please assign me with this. @jayk-gupta

**Comment by jayk-gupta** [comment]
# Important Announcement: Closure of GitHub Repository Issues, Website Redesign, and Discord Channel Invitation
We apologize for the inconvenience caused, but we must inform you that all current issues in our repository will be closed. This decision aims to improve our development process and enhance organization.

Excitingly, we are announcing a complete redesign of our website, focused on improving user experience and incorporating new features aligned with our goals.

Please note that approximately half of the existing issues are redundant and will be closed accordingly.

We also invite you to join our Discord channel for project collaboration and communication. Visit GSSoC server and assign yourself Web Resource Hub project role using the self-roles feature.

[Join here](https://discord.com/channels/1099745007172329592/1110637817383632957)

Your feedback and support are invaluable to us. We look forward to hearing your thoughts on the upcoming changes.

Thank you for your understanding and continued support.

Sincerely,
Project Admin
