### ISSUE TITLE
[STYLE] what about adding A dark theme

### ISSUE THREAD

**Issue by Ankittap2001** [jayk-gupta/web-resources-project#39]
i want to contribute from gssoc23 website will look more ui good.

**Comment by jayk-gupta** [comment]
Yes, you can add!

**Comment by Ankittap2001** [comment]
ok thank you

**Comment by Eninini** [comment]
Can I also contribute to this issue?

**Comment by jayk-gupta** [comment]
> ok thank you

Are you working on it?

**Comment by jayk-gupta** [comment]
# Important Announcement: Closure of GitHub Repository Issues, Website Redesign, and Discord Channel Invitation
We apologize for the inconvenience caused, but we must inform you that all current issues in our repository will be closed. This decision aims to improve our development process and enhance organization.

Excitingly, we are announcing a complete redesign of our website, focused on improving user experience and incorporating new features aligned with our goals.

Please note that approximately half of the existing issues are redundant and will be closed accordingly.

We also invite you to join our Discord channel for project collaboration and communication. Visit GSSoC server and assign yourself Web Resource Hub project role using the self-roles feature.

[Join here](https://discord.com/channels/1099745007172329592/1110637817383632957)

Your feedback and support are invaluable to us. We look forward to hearing your thoughts on the upcoming changes.

Thank you for your understanding and continued support.

Sincerely,
Project Admin
