### ISSUE TITLE
[FEAT]: WEB3 

### ISSUE THREAD

**Issue by Atharva-3000** [jayk-gupta/web-resources-project#40]
**Is your feature request related to a problem? Please describe.**
No resources **related to WEB3**, **I would love to put up and add some resources** regarding that, from **tools to videos** and everything. 

**Describe the solution you'd like**
I want to **add resources for WEB3**. Since the industry of WEB3 is booming right now, I think it should be very helpful for people who wanna enter this market.

**Comment by jayk-gupta** [comment]
Not planning to add it for now!

**Comment by Atharva-3000** [comment]
ok, no probs
