### ISSUE TITLE
[FEAT] Adding Hover Effects on the Card Components

### ISSUE THREAD

**Issue by abhinav-m22** [jayk-gupta/web-resources-project#41]
In the card components of the Resources Section, adding some hover effects and animations can improve the UX and a seamless experience to the user.
Also there is some text underflow in these card components which can be resolved.
I want to work on the feature suggested.

Please assign me the task under GSSoC'23.

**Comment by itsPriyanshuhere** [comment]
Adding the hover effect would make the project look more attractive. I am a MERN stack developer and can make some changes to the UI. Can you assign me this task under GSSoC'23.

**Comment by jayk-gupta** [comment]
# Important Announcement: Closure of GitHub Repository Issues, Website Redesign, and Discord Channel Invitation
We apologize for the inconvenience caused, but we must inform you that all current issues in our repository will be closed. This decision aims to improve our development process and enhance organization.

Excitingly, we are announcing a complete redesign of our website, focused on improving user experience and incorporating new features aligned with our goals.

Please note that approximately half of the existing issues are redundant and will be closed accordingly.

We also invite you to join our Discord channel for project collaboration and communication. Visit GSSoC server and assign yourself Web Resource Hub project role using the self-roles feature.

[Join here](https://discord.com/channels/1099745007172329592/1110637817383632957)

Your feedback and support are invaluable to us. We look forward to hearing your thoughts on the upcoming changes.

Thank you for your understanding and continued support.

Sincerely,
Project Admin
