### ISSUE TITLE
[FEAT]: Add BFE.dev Website for Practicing Challenges in CSS,JavaSript,React.js Categories

### ISSUE THREAD

**Issue by NarendraKoya999** [jayk-gupta/web-resources-project#418]
**Is your feature request related to a problem? Please describe.**
## GSSOC'23
- **` Add BFE.dev Website for Practicing Challenges in CSS, JavaScript, React.js`**
**Describe the solution you'd like**
- **`Add BFE.dev Website in CSS, JavaScript, React.js Categories for Practicing Challenges Effectively`**
**Describe alternatives you've considered**

**Additional context**
- **` I want to Work on this Issue`**

**Comment by jayk-gupta** [comment]
Please do not spam!!!
