### ISSUE TITLE
[FEAT]: Add sitepoint for Practicing and Learning HTML,CSS, JavaScript Technologies

### ISSUE THREAD

**Issue by NarendraKoya999** [jayk-gupta/web-resources-project#421]
**Is your feature request related to a problem? Please describe.**
### GSSOC'23
- **`Add sitepoint Website for Practicing and Learning HTML, CSS, JavaScript Technologies.`**

**Describe the solution you'd like**
- **`This sitepoint is adding in HTML, CSS, JavaScript Categories of Challenges Section `**

**Describe alternatives you've considered**

**Additional context**
- **` I want to work on this Issue`**

**Comment by jayk-gupta** [comment]
Please close all issues and create one!!

**Comment by NarendraKoya999** [comment]
Hi @jayk-gupta . You tell Whatever Currently Closed Issues. All that Issues Clubbed in One Issue .Am I Right?
