### ISSUE TITLE
Add "About" Section to Website

### ISSUE THREAD

**Issue by M-A-N-I-K** [jayk-gupta/web-resources-project#43]
Hi everyone,

I'm proposing that we add an "About" section to the website. This section could include information about the project's goals, the team behind the project, and how people can get involved.

I think an "About" section would be useful for several reasons:

-     It would give visitors to the website more information about the project and its creators. This could help to build trust and credibility with visitors, and it could also help to attract new contributors.
-     It would help to clarify the project's goals and objectives. This could help to ensure that everyone is on the same page and working towards the same goals.
-     It would provide a space for the team to share their vision for the project. This could help to inspire and motivate others to get involved.

I'm happy to help with the creation of the "About" section if needed.

Thanks,
Manik Dingra

**Comment by jayk-gupta** [comment]
# Important Announcement: Closure of GitHub Repository Issues, Website Redesign, and Discord Channel Invitation
We apologize for the inconvenience caused, but we must inform you that all current issues in our repository will be closed. This decision aims to improve our development process and enhance organization.

Excitingly, we are announcing a complete redesign of our website, focused on improving user experience and incorporating new features aligned with our goals.

Please note that approximately half of the existing issues are redundant and will be closed accordingly.

We also invite you to join our Discord channel for project collaboration and communication. Visit GSSoC server and assign yourself Web Resource Hub project role using the self-roles feature.

[Join here](https://discord.com/channels/1099745007172329592/1110637817383632957)

Your feedback and support are invaluable to us. We look forward to hearing your thoughts on the upcoming changes.

Thank you for your understanding and continued support.

Sincerely,
Project Admin
