### ISSUE TITLE
Implement backend of App

### ISSUE THREAD

**Issue by Ahtaxam** [jayk-gupta/web-resources-project#45]
I want to implement backend of app in **Node.js** so our data store in database like mongoDB. and also on each section a button so user can add new recources . How do you think?

**NOTE:** I would like to work on this under GSSOC'23.

**Comment by Ahtaxam** [comment]
@jayk-gupta ?

**Comment by jayk-gupta** [comment]
Can you do this?

**Comment by Ahtaxam** [comment]
yes. I can. but it will take some time

**Comment by jayk-gupta** [comment]
Shall I assign you it?

**Comment by salted0dreams** [comment]
Hey, can i collaborate in this issue as well?

**Comment by Ahtaxam** [comment]
> Shall I assign you it?

yes.

**Comment by Uj293** [comment]
I can also help in this task as i already hosted one of my app on render and used mongodb atlas to store the data.
please assign this to me under GSSOC 2023

**Comment by jayk-gupta** [comment]
# Important Announcement: Closure of GitHub Repository Issues, Website Redesign, and Discord Channel Invitation
We apologize for the inconvenience caused, but we must inform you that all current issues in our repository will be closed. This decision aims to improve our development process and enhance organization.

Excitingly, we are announcing a complete redesign of our website, focused on improving user experience and incorporating new features aligned with our goals.

Please note that approximately half of the existing issues are redundant and will be closed accordingly.

We also invite you to join our Discord channel for project collaboration and communication. Visit GSSoC server and assign yourself Web Resource Hub project role using the self-roles feature.

[Join here](https://discord.com/channels/1099745007172329592/1110637817383632957)

Your feedback and support are invaluable to us. We look forward to hearing your thoughts on the upcoming changes.

Thank you for your understanding and continued support.

Sincerely,
Project Admin
