### ISSUE TITLE
[STYLE] style home page 

### ISSUE THREAD

**Issue by RitiChandak** [jayk-gupta/web-resources-project#484]
Is your feature request related to a problem? Please describe.
![image](https://github.com/jayk-gupta/web-resources-project/assets/96969496/c1ef7203-6e97-4c5a-95ff-68617d7c0328)

Describe the solution you'd like

![image](https://github.com/jayk-gupta/web-resources-project/assets/96969496/7f1c7525-7f45-401d-9ffe-dd6d60f49e4d)
making it more vibrant and accoriding to color of website

**Comment by jayk-gupta** [comment]
Actually the home page will be changed, so don't need to change it
