### ISSUE TITLE
[STYLE]: Adding hamburger option instead of the whole sidebar

### ISSUE THREAD

**Issue by Akanksha-202** [jayk-gupta/web-resources-project#49]
Is your feature request related to a problem? Please describe.
The sidebar is there while using the website for learning purposes. Which takes quite a bit size of the screen.
Describe the solution you'd like
I would like to add a toggle option for the sidebar using the hamburger option so that the sidebar can be toggled and collapsed according to the user's wish.

**Comment by jayk-gupta** [comment]
yes I was thinking about it.
Would like to work on it?

**Comment by Akanksha-202** [comment]
> yes I was thinking about it.
> Would like to work on it?

Yeah sure!
Please assign under GSSoC label^⁠_⁠^

**Comment by Akanksha-202** [comment]
Hey, I have made the PR, kindly review
