### ISSUE TITLE
[FEAT] Add a 404 not found page [GSSoC'23] 

### ISSUE THREAD

**Issue by Sukhendu2002** [jayk-gupta/web-resources-project#51]
Add a custom 404 not found page
Can you assign this to me, I want to work on this under GSSoC'23

**Comment by jayk-gupta** [comment]
What is need of 404 not found?

**Comment by Sukhendu2002** [comment]
Nowadays, every modern website should have a custom 404 page to improve user experience and guide users when they encounter broken links or non-existent pages.

**Comment by PayalPadmalyaPrusty** [comment]
@jayk-gupta I want to contribute.Please assign me

**Comment by jayk-gupta** [comment]
# Important Announcement: Closure of GitHub Repository Issues, Website Redesign, and Discord Channel Invitation
We apologize for the inconvenience caused, but we must inform you that all current issues in our repository will be closed. This decision aims to improve our development process and enhance organization.

Excitingly, we are announcing a complete redesign of our website, focused on improving user experience and incorporating new features aligned with our goals.

Please note that approximately half of the existing issues are redundant and will be closed accordingly.

We also invite you to join our Discord channel for project collaboration and communication. Visit GSSoC server and assign yourself Web Resource Hub project role using the self-roles feature.

[Join here](https://discord.com/channels/1099745007172329592/1110637817383632957)

Your feedback and support are invaluable to us. We look forward to hearing your thoughts on the upcoming changes.

Thank you for your understanding and continued support.

Sincerely,
Project Admin
