### ISSUE TITLE
[STYLE] Add a better images to index.html file (home page) for better appealing UI

### ISSUE THREAD

**Issue by Abhinavcode13** [jayk-gupta/web-resources-project#52]

**Comment by karthik2004315** [comment]
@peb-peb can I work on this please I will change the home page photo

**Comment by jayk-gupta** [comment]
> _No description provided._

How?

**Comment by Abhinavcode13** [comment]
Adding high-quality images that align with the aesthetic and purpose of your website @jayk-gupta

**Comment by swati323ch** [comment]
We can add a better image which would be more relevant to the content of the website and would be viewer oriented. This will make the website look more professional and appealing, and it will help to attract more visitors.

**Comment by jayk-gupta** [comment]
# Important Announcement: Closure of GitHub Repository Issues, Website Redesign, and Discord Channel Invitation
We apologize for the inconvenience caused, but we must inform you that all current issues in our repository will be closed. This decision aims to improve our development process and enhance organization.

Excitingly, we are announcing a complete redesign of our website, focused on improving user experience and incorporating new features aligned with our goals.

Please note that approximately half of the existing issues are redundant and will be closed accordingly.

We also invite you to join our Discord channel for project collaboration and communication. Visit GSSoC server and assign yourself Web Resource Hub project role using the self-roles feature.

[Join here](https://discord.com/channels/1099745007172329592/1110637817383632957)

Your feedback and support are invaluable to us. We look forward to hearing your thoughts on the upcoming changes.

Thank you for your understanding and continued support.

Sincerely,
Project Admin
