### ISSUE TITLE
[BUG] It should be proper responsive for mobile devices...

### ISSUE THREAD

**Issue by Brijesh1963** [jayk-gupta/web-resources-project#536]
**Describe the bug**
 It should be proper responsive for mobile devices...

**To Reproduce**
1. Go to 'https://web-resources-hub-project.vercel.app/'

**Expected behavior**
Its should be proper responsive for mobile device..
![responsiveness2](https://github.com/jayk-gupta/web-resources-project/assets/98037970/1641092a-5514-4f4a-9bb0-ef793bec3c8c)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jayk-gupta** [comment]
That PR is in review, will merge it soon
