### ISSUE TITLE
[STYLE] Site is completely non responsive

### ISSUE THREAD

**Issue by raghavawasthi24** [jayk-gupta/web-resources-project#54]
![Screenshot (100)](https://github.com/jayk-gupta/web-resources-project/assets/113261155/db6b3d8c-7bae-44ed-8061-0397318af39b)

The site isn't responsive in other devices.

How I will fix?
With the help of the CSS, I will make it responsive which will be completely visible on other devices. 

I request you to assign this issue to me.

**Comment by mhdamaan79** [comment]
Someone else has already mentioned the same issue.
