### ISSUE TITLE
Addition of Footer Section with a better ui and will also have a contact us section

### ISSUE THREAD

**Issue by sajalbatra** [jayk-gupta/web-resources-project#55]
**Is your feature request related to a problem? Please describe.**
The absence of a footer section on the website is causing a lack of important information and functionality. Users are unable to access key details and contact options, leading to a less user-friendly experience.

**Describe the solution you'd like**
I would like to add a footer section to the website. The footer should have a visually appealing design and provide essential information and contact options for users. It should include sections such as "About Us," "Contact Us," "Terms and Conditions," "Privacy Policy," and any other relevant links or sections. The "Contact Us" section should include contact details like email, phone number, address, and possibly a form for users to submit inquiries or messages.

**Describe alternatives you've considered**
An alternative solution would be to include the footer information within the main content area of the website. However, this approach may clutter the page and distract users from the main content. Having a dedicated footer section keeps the design clean and organized.

**Additional context**
It would be helpful to provide any specific requirements or preferences for the footer's design, such as color schemes, typography, or branding guidelines. Additionally, if there are any existing sections or information that should be included in the footer, please provide details or examples.

**Comment by jayk-gupta** [comment]
# Important Announcement: Closure of GitHub Repository Issues, Website Redesign, and Discord Channel Invitation
We apologize for the inconvenience caused, but we must inform you that all current issues in our repository will be closed. This decision aims to improve our development process and enhance organization.

Excitingly, we are announcing a complete redesign of our website, focused on improving user experience and incorporating new features aligned with our goals.

Please note that approximately half of the existing issues are redundant and will be closed accordingly.

We also invite you to join our Discord channel for project collaboration and communication. Visit GSSoC server and assign yourself Web Resource Hub project role using the self-roles feature.

[Join here](https://discord.com/channels/1099745007172329592/1110637817383632957)

Your feedback and support are invaluable to us. We look forward to hearing your thoughts on the upcoming changes.

Thank you for your understanding and continued support.

Sincerely,
Project Admin
