### ISSUE TITLE
Making the landing page responsive 

### ISSUE THREAD

**Issue by AmanSingh6574** [jayk-gupta/web-resources-project#56]
![Screenshot_2023-05-21-10-09-00-71_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/jayk-gupta/web-resources-project/assets/113782984/c87e5811-89d4-46d5-b748-6048dd5288b0)

kindly assign me this task to contribute in desired changes under GSSoC'23 @mhdamaan79

**Comment by jayk-gupta** [comment]
Already assigned to someone
