### ISSUE TITLE
[BUG] - Resolve "Each child in a list should have a unique 'key' prop" Warning

### ISSUE THREAD

**Issue by devasyarajguru** [jayk-gupta/web-resources-project#67]
**Describe the bug**
The bug is a warning message indicating that each child within a list should have a unique "key" prop. This warning is triggered when rendering components or elements in a list without assigning a unique identifier to each item using the "key" prop. The bug report aims to resolve this issue by adding the necessary "key" props to ensure proper rendering and performance optimization within the list.

**To Reproduce**
1. Go to 'inspect'
2. Click on 'console'
3. Scroll down to 'bottom'

**Expected behavior**
The expected behavior is for each child component or element within the list to have a unique "key" prop assigned to it. This ensures proper rendering and performance optimization. By providing unique keys, the warning message "Each child in a list should have a unique 'key' prop" should no longer appear.

**Screenshots**
<img width="959" alt="bugs" src="https://github.com/jayk-gupta/web-resources-project/assets/84851506/cd45c778-42cc-4ccc-9ca2-dc8d41dcd507">

**Desktop (please complete the following information):**
 - OS: [e.g. Widnows]
 - Browser [chrome]
 - Version [113.0.5672.127]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jayk-gupta** [comment]
# Important Announcement: Closure of GitHub Repository Issues, Website Redesign, and Discord Channel Invitation
We apologize for the inconvenience caused, but we must inform you that all current issues in our repository will be closed. This decision aims to improve our development process and enhance organization.

Excitingly, we are announcing a complete redesign of our website, focused on improving user experience and incorporating new features aligned with our goals.

Please note that approximately half of the existing issues are redundant and will be closed accordingly.

We also invite you to join our Discord channel for project collaboration and communication. Visit GSSoC server and assign yourself Web Resource Hub project role using the self-roles feature.

[Join here](https://discord.com/channels/1099745007172329592/1110637817383632957)

Your feedback and support are invaluable to us. We look forward to hearing your thoughts on the upcoming changes.

Thank you for your understanding and continued support.

Sincerely,
Project Admin
