### ISSUE TITLE
Improving the Books Section....[BUG] 

### ISSUE THREAD

**Issue by RahulRana701** [jayk-gupta/web-resources-project#68]
I would like to work create some spacing between these containers and add different images in it which will make the UI better.
I will do it for each part in books section that is for html, css, javascript and react.......
<br> 
<img width="901" alt="Screenshot 2023-05-21 134229" src="https://github.com/jayk-gupta/web-resources-project/assets/123585591/1dd2dc3e-66d1-4cf1-a389-4be5a52d0d05">

HI @jayk-gupta I would like to work on this issue please assign it to me..............

**Comment by jayk-gupta** [comment]
It is being worked on responsiveness by someone
