### ISSUE TITLE
Navbar Element Overflow

### ISSUE THREAD

**Issue by 9520prashant** [jayk-gupta/web-resources-project#7]
![Screenshot (220)](https://github.com/jayk-gupta/web-resources-project/assets/99237795/8e00e652-5b27-4f22-86dc-81573859fb37)

Hey @jayk-gupta I Found this issue in Navbar assign me if this is correct issue.

**Comment by jayk-gupta** [comment]
Yes, I am working on it

**Comment by jayk-gupta** [comment]
done!
