### ISSUE TITLE
[FEAT] Opening of the websites

### ISSUE THREAD

**Issue by jayasree-g** [jayk-gupta/web-resources-project#72]
Hello, I'm a **GSSOC'23 contributor**.
Currently, the websites only open when I click directly on the name of the website, but not when I click anywhere else on the card. It would be more user-friendly if the entire card was clickable.

I would like to work on that and also add a link icon to each card to signify that the website link will open in a new window when clicked.

**Comment by jayk-gupta** [comment]
I don't think that's a good idea, you can add on images tho!

**Comment by jayk-gupta** [comment]
# Important Announcement: Closure of GitHub Repository Issues, Website Redesign, and Discord Channel Invitation
We apologize for the inconvenience caused, but we must inform you that all current issues in our repository will be closed. This decision aims to improve our development process and enhance organization.

Excitingly, we are announcing a complete redesign of our website, focused on improving user experience and incorporating new features aligned with our goals.

Please note that approximately half of the existing issues are redundant and will be closed accordingly.

We also invite you to join our Discord channel for project collaboration and communication. Visit GSSoC server and assign yourself Web Resource Hub project role using the self-roles feature.

[Join here](https://discord.com/channels/1099745007172329592/1110637817383632957)

Your feedback and support are invaluable to us. We look forward to hearing your thoughts on the upcoming changes.

Thank you for your understanding and continued support.

Sincerely,
Project Admin
