### ISSUE TITLE
[FEAT] Addding Search feature in Home Page

### ISSUE THREAD

**Issue by komalioruganti** [jayk-gupta/web-resources-project#74]
**Is your feature request related to a problem? Please describe.**
In order to find a particular feature, a user has to go through all the tabs and find the resources he/she wishes to find. This is quite frustrating and makes it extremely difficult to find the particular resource they came to search in the first place.

**Describe the solution you'd like**
I think adding a search feature would solve this issue and help in navigating and finding resources easily.

**Describe alternatives you've considered**
The other alternative could be adding a dropdown to every resource page for HTML, CSS, Javascript, and React. The dropdown would contain all the resources that come under that specific section. But I think adding both the search feature and dropdown menu would be quite appreciated.

**Additional context**
![image](https://github.com/jayk-gupta/web-resources-project/assets/95839946/6b8ab487-1f7e-46cd-af9c-70de5a818e8f)

**Comment by KandepiBhavani23** [comment]
I would like to work on this issue under GSSoC'23. Please assign it to me

**Comment by jayk-gupta** [comment]
> **Is your feature request related to a problem? Please describe.** In order to find a particular feature, a user has to go through all the tabs and find the resources he/she wishes to find. This is quite frustrating and makes it extremely difficult to find the particular resource they came to search in the first place.
> 
> **Describe the solution you'd like** I think adding a search feature would solve this issue and help in navigating and finding resources easily.
> 
> **Describe alternatives you've considered** The other alternative could be adding a dropdown to every resource page for HTML, CSS, Javascript, and React. The dropdown would contain all the resources that come under that specific section. But I think adding both the search feature and dropdown menu would be quite appreciated.
> 
> **Additional context** ![image](https://user-images.githubusercontent.com/95839946/239734413-6b8ab487-1f7e-46cd-af9c-70de5a818e8f.png)

Can you implement search feature?

**Comment by KandepiBhavani23** [comment]
Yes I would like to implement this feature

**Comment by komalioruganti** [comment]
I have already started working on it. Can you please assign it to me?

**Comment by komalioruganti** [comment]
I can implement a search feature

**Comment by komalioruganti** [comment]
Can you add the Gssoc23 tag to this issue?

**Comment by jayk-gupta** [comment]
# Important Announcement: Closure of GitHub Repository Issues, Website Redesign, and Discord Channel Invitation
We apologize for the inconvenience caused, but we must inform you that all current issues in our repository will be closed. This decision aims to improve our development process and enhance organization.

Excitingly, we are announcing a complete redesign of our website, focused on improving user experience and incorporating new features aligned with our goals.

Please note that approximately half of the existing issues are redundant and will be closed accordingly.

We also invite you to join our Discord channel for project collaboration and communication. Visit GSSoC server and assign yourself Web Resource Hub project role using the self-roles feature.

[Join here](https://discord.com/channels/1099745007172329592/1110637817383632957)

Your feedback and support are invaluable to us. We look forward to hearing your thoughts on the upcoming changes.

Thank you for your understanding and continued support.

Sincerely,
Project Admin
