### ISSUE TITLE
Request to Add Additional Resources (TypeScript, Next.js, etc.)

### ISSUE THREAD

**Issue by abhijeetnishal** [jayk-gupta/web-resources-project#75]
**Issue Description**
I am writing to propose an enhancement to the project by incorporating additional resources such as TypeScript, Next.js, Node.js, and related technologies. 

**Benefits of Adding this Resource**
These technologies have gained significant popularity in recent years due to their numerous advantages, and integrating them into the project would greatly benefit its development, maintainability, and overall user experience. 
By adding these resources to the project, you would not only keep up with the latest trends in web development but also attract a broader audience of developers who are familiar with or interested in these technologies. It would enhance the project's accessibility, encourage community contributions, and potentially lead to more robust and innovative features.

@jayk-gupta  Please assign me this issue under GSSOC2023

**Comment by jayk-gupta** [comment]
Yeah, actually some layout issues are there which needs to be resolved after that you can add it.

**Comment by abhijeetnishal** [comment]
Is anyone working on that issue and when will be that issue is resolved @jayk-gupta

**Comment by jayk-gupta** [comment]
# Important Announcement: Closure of GitHub Repository Issues, Website Redesign, and Discord Channel Invitation
We apologize for the inconvenience caused, but we must inform you that all current issues in our repository will be closed. This decision aims to improve our development process and enhance organization.

Excitingly, we are announcing a complete redesign of our website, focused on improving user experience and incorporating new features aligned with our goals.

Please note that approximately half of the existing issues are redundant and will be closed accordingly.

We also invite you to join our Discord channel for project collaboration and communication. Visit GSSoC server and assign yourself Web Resource Hub project role using the self-roles feature.

[Join here](https://discord.com/channels/1099745007172329592/1110637817383632957)

Your feedback and support are invaluable to us. We look forward to hearing your thoughts on the upcoming changes.

Thank you for your understanding and continued support.

Sincerely,
Project Admin
