### ISSUE TITLE
[STYLE] CARDS ARE OVERLAPING AND EFFECTS ARE NOT SMOOTH

### ISSUE THREAD

**Issue by ashutoshgithubs** [jayk-gupta/web-resources-project#76]
Is your feature request related to a problem? Please describe.
I observed that cards are overlapping from side to each other and also there is a sudden jerk while hovering. Also, it is not responsive.

Describe the solution you'd like
 I will add proper margins and gaps between cards and will add smooth transition and hovering effects and make it responsive too.

Describe alternatives you've considered.
Cards with proper margin.

Additional context
Please have a look at my cloned website and go through all its cards to get a pleasant user experience.
[https://razorpayclonebyashu.netlify.app/](url)

![SC](https://github.com/jayk-gupta/web-resources-project/assets/97340498/5992e88d-4d24-442b-834d-570b286cc3a8)

**Comment by ashutoshgithubs** [comment]
@jayk-gupta I will solve this issue. So please assign me this task. 
Thank you.

**Comment by jayk-gupta** [comment]
# Important Announcement: Closure of GitHub Repository Issues, Website Redesign, and Discord Channel Invitation
We apologize for the inconvenience caused, but we must inform you that all current issues in our repository will be closed. This decision aims to improve our development process and enhance organization.

Excitingly, we are announcing a complete redesign of our website, focused on improving user experience and incorporating new features aligned with our goals.

Please note that approximately half of the existing issues are redundant and will be closed accordingly.

We also invite you to join our Discord channel for project collaboration and communication. Visit GSSoC server and assign yourself Web Resource Hub project role using the self-roles feature.

[Join here](https://discord.com/channels/1099745007172329592/1110637817383632957)

Your feedback and support are invaluable to us. We look forward to hearing your thoughts on the upcoming changes.

Thank you for your understanding and continued support.

Sincerely,
Project Admin
