### ISSUE TITLE
Propsosal for addition of new resources (UI & UX)

### ISSUE THREAD

**Issue by urz-ahmed** [jayk-gupta/web-resources-project#79]
**Issue Description**
Addition of new resources which is UI & UX which will benefit front end developer and UI & UX designers.

**Resource Details**
**Resource Type:** [Video/Website/Challenge/Tool/Books/Other]  
**Title/Name of the Resource:** UI & UX  
**Description:*I will add resources related to UI & UX designing.*   

**Topic or Category**
1) Vector Art
2) Animations
3) Fonts
4) Colors

**Intended Audience (optional)**
beginners, intermediate, advanced

**Benefits of Adding this Resource**
This will benefit to the audience who wants to learn UI & UX designing.

**Checklist (optional)**
- [ x] I have conducted a search to ensure this resource is not a duplicate.
- [x ] I confirm that this resource complies with the guidelines and policies of the project/repository.
Please assign me this issue under gssoc'2023

**Comment by jayk-gupta** [comment]
Wait for sometime, The UI of the project needs to be improved first.
