### ISSUE TITLE
[FEAT] Adding web dev roadmap to the website

### ISSUE THREAD

**Issue by Isha988** [jayk-gupta/web-resources-project#81]
**Is your feature request related to a problem? Please describe.**
Basically, this website is for complete beginner and beginners usually have confusion of what to learn next. So a roadmap section will be a good  feature to add in the application.

**Describe the solution you'd like**
In the left menu bar, there should a icon for roadmap. On roadmap page, there should a roadmap with detailed list of topics to be covered in technology like, if step 1 is learning HTML so there must a detailed list of topics to be learn in HTML, same for CSS and JS and other technology even for backend stuff.

**Describe alternatives you've considered**
For alternative solution we can add links to different roadmap articles and videos available on internet on roadmap page, 

**Additional context**

**Is this issue already present ?**
No

**Do you working on it?**
I want to work on this feature under GSSOC'23

**Comment by jayk-gupta** [comment]
Yes you can add it, I will created folders for it.
Then you can add the resources
