### ISSUE TITLE
[FEAT] Adding View Site : Buttons for all section cards. 

### ISSUE THREAD

**Issue by abhi03ruchi** [jayk-gupta/web-resources-project#82]
**Is your feature request related to a problem? Please describe.**
The user may not be able to figure out how to access these resources through the site. So I would create a button by which users can easily go to the required resource and utilise/ access it. 

**Describe the solution you'd like**
eg: making buttons for accessing these particular resources.
<img width="1261" alt="Screenshot 2023-05-21 at 9 11 37 PM" src="https://github.com/jayk-gupta/web-resources-project/assets/105661636/b47b9810-9607-4a73-b823-ebe9ac432c8f">

- I would like to create a view more \ view resource **button** through which the user can actually visit the website/challenge/video of various web development tools - HTML, CSS, javascript and react. 
-  Redesign / Change the UI  of all cards to enhance user experience and make the website more compelling and memorable to visitors.

**Additional context**
I am well versed in react js, HTML, CSS and javascript. Plz, assign this task to me under GSSOC'23.

**Comment by jayk-gupta** [comment]
# Important Announcement: Closure of GitHub Repository Issues, Website Redesign, and Discord Channel Invitation
We apologize for the inconvenience caused, but we must inform you that all current issues in our repository will be closed. This decision aims to improve our development process and enhance organization.

Excitingly, we are announcing a complete redesign of our website, focused on improving user experience and incorporating new features aligned with our goals.

Please note that approximately half of the existing issues are redundant and will be closed accordingly.

We also invite you to join our Discord channel for project collaboration and communication. Visit GSSoC server and assign yourself Web Resource Hub project role using the self-roles feature.

[Join here](https://discord.com/channels/1099745007172329592/1110637817383632957)

Your feedback and support are invaluable to us. We look forward to hearing your thoughts on the upcoming changes.

Thank you for your understanding and continued support.

Sincerely,
Project Admin
