### ISSUE TITLE
[STYLE]

### ISSUE THREAD

**Issue by Eninini** [jayk-gupta/web-resources-project#88]
Is your feature request related to a problem? Please describe.

1.The Home page images are not in alignment with the text in my phone as well as my laptop.
2. The fonts do not go well with each other.
3. There is a lot of spacing around in the phone screen but the text appears congested.

Describe the solution you'd like

1.Alternative images whose alignment does not depend on the text alignment. 
2. Better fonts.
3. Making containers and their size adaptive to screen size instead of just using <br>

Additional context
![Screenshot_20230521_233120_Chrome](https://github.com/jayk-gupta/web-resources-project/assets/100461681/9a3f6083-28d3-45a9-ad57-6edb0e4a3505)

**Comment by jayk-gupta** [comment]
# Important Announcement: Closure of GitHub Repository Issues, Website Redesign, and Discord Channel Invitation
We apologize for the inconvenience caused, but we must inform you that all current issues in our repository will be closed. This decision aims to improve our development process and enhance organization.

Excitingly, we are announcing a complete redesign of our website, focused on improving user experience and incorporating new features aligned with our goals.

Please note that approximately half of the existing issues are redundant and will be closed accordingly.

We also invite you to join our Discord channel for project collaboration and communication. Visit GSSoC server and assign yourself Web Resource Hub project role using the self-roles feature.

[Join here](https://discord.com/channels/1099745007172329592/1110637817383632957)

Your feedback and support are invaluable to us. We look forward to hearing your thoughts on the upcoming changes.

Thank you for your understanding and continued support.

Sincerely,
Project Admin
