### ISSUE TITLE
[STYLE]

### ISSUE THREAD

**Issue by Soumyajit2825** [jayk-gupta/web-resources-project#89]
Responsiveness issue of the Website page
The page is not responsive in mobile view.
I want to add responsiveness int the Website page where the website names are showing for the particular tech stacks
![Screenshot 2023-05-22 003846](https://github.com/jayk-gupta/web-resources-project/assets/100519291/930e1b95-e509-4c7d-b1b4-288e7b20746d)

I can also work on the whole website for making it fully responsive

**Comment by jayk-gupta** [comment]
This issue has already being raised
