### ISSUE TITLE
Add a JavaScript resource

### ISSUE THREAD

**Issue by ARYAN-CODES-STAR** [jayk-gupta/web-resources-project#91]
**Issue Description**
Please provide a clear and concise description of the resource you would like to add, including the topic or category it pertains to.

**Resource Details**
**Resource Type:** [Video/Website/Challenge/Tool/Books/Other]  
**Title/Name of the Resource:** [Enter the title or name]  
**Description:** [Briefly describe the content and relevance of the resource]  
**URL or Source:** [Provide the link to the resource or mention the source]

**Topic or Category**
Specify the topic or category that best represents the subject matter of the resource.

**Intended Audience (optional)**
Who is the intended audience for this resource? (e.g., beginners, intermediate, advanced, researchers)

**Benefits of Adding this Resource**
Explain how this resource would be valuable to users and contributors of the project/repository.

**Additional Information (optional)**
Include any additional information or context that might be helpful for evaluating the resource or understanding its relevance.

**Checklist (optional)**
- [ ] I have conducted a search to ensure this resource is not a duplicate.
- [ ] I confirm that this resource complies with the guidelines and policies of the project/repository.

**Comment by jayk-gupta** [comment]
What u want to add?
