### ISSUE TITLE
[FEAT] Adding a new CheatSheet section for this project

### ISSUE THREAD

**Issue by Shreyas-SAS** [jayk-gupta/web-resources-project#94]
### Is your feature request related to a problem? Please describe.
Usually, as a learner, it is hard to grasp the large number of resources we have, and most miss creating concise notes for each of these.

### **Describe the solution you'd like**
In such cases, a cheat sheet can give a quick reference or a recap that can be a valuable resource for the learner. I propose to add the same to this website. I also have a few cheat sheets ready to deploy, but I will add them as a separate issue on approval since it is a separate topic.

### **Describe alternatives you've considered**
We could add links to a cheat sheet as a resource under all the topic tags if creating a new section is not a good idea.

### **Additional context**
You are welcome to view some of my blog-based cheat sheets for reference here:
1. [Git-Cheatsheet](https://iq.opengenus.org/git-commands-list/)
2. [npm-Cheatsheet](https://iq.opengenus.org/npm-commands/)
3. [powershell-Cheatsheet](https://iq.opengenus.org/powershell-commands-list/)
4. [HTML-Cheatsheet](https://iq.opengenus.org/html-tags-list/)
I also have Javascript, Typescript, and React cheat sheets, but they aren't deployed yet. For other than the above 7 topics we may also open contributions to other contributors.

If you are OK with the arrangement, please assign me the issue. I will create seven different issues with each topic cheat sheet so that I am assigned to them on per First Come, First Serve Basis.

**Comment by jayk-gupta** [comment]
# Important Announcement: Closure of GitHub Repository Issues, Website Redesign, and Discord Channel Invitation
We apologize for the inconvenience caused, but we must inform you that all current issues in our repository will be closed. This decision aims to improve our development process and enhance organization.

Excitingly, we are announcing a complete redesign of our website, focused on improving user experience and incorporating new features aligned with our goals.

Please note that approximately half of the existing issues are redundant and will be closed accordingly.

We also invite you to join our Discord channel for project collaboration and communication. Visit GSSoC server and assign yourself Web Resource Hub project role using the self-roles feature.

[Join here](https://discord.com/channels/1099745007172329592/1110637817383632957)

Your feedback and support are invaluable to us. We look forward to hearing your thoughts on the upcoming changes.

Thank you for your understanding and continued support.

Sincerely,
Project Admin
